spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            - id: product-service-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=0

            - id: product-service-admin-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/admin/product/**
              filters:
                - AdminValidation
                - StripPrefix=0

            - id: inventory-service-admin-route
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**
              filters:
                - AdminValidation
                - StripPrefix=0

            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/cart/** , /order/**
              filters:
                - JwtValidation
                - StripPrefix=0

            - id: order-service-admin-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/admin/order/**
              filters:
                - AdminValidation
                - StripPrefix=0

            - id: api-docs-user-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

            - id: api-docs-product-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api-docs/product
              filters:
                - RewritePath=/api-docs/product,/v3/api-docs

            - id: api-docs-inventory-route
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api-docs/inventory
              filters:
                - RewritePath=/api-docs/inventory,/v3/api-docs

            - id: api-docs-order-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api-docs/order
              filters:
                - RewritePath=/api-docs/order,/v3/api-docs

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8080
auth:
  service:
    url: ${USER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

    otlp:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans