spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8084

jwt:
  secret: ${JWT_SECRET}

mail:
  email: ${MAIL_USERNAME}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

    otlp:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans